theme: minima

# Setup
name:                "Your site name" # change me
description:         "Awesome description" # change me
url:                 "https://change.me" # change me
baseurl:             "/change_me" # change me
author:
#  name:              "Your Name" # change me
#  email:             "your@email.com" # change me

# Exclude
#
# Exclude some files to not compiled by Jekyll
exclude:
  # Gemfile used only on local
  - Gemfile
  - Gemfile.lock
  - README.md

# Supported plugins by github pages
# Check here: https://pages.github.com/versions/
gems:
  - jekyll-feed
  - jekyll-sitemap

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  style:             compressed

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# compress compiled html
# more: https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

# prose config
prose:
  rooturl: _posts
  siteurl: https://akhyarrh.github.io/jekyll-boilerplate # change me
  media: uploads # folder use by Prose
  relativeLinks: https://akhyarrh.github.io/jekyll-boilerplate/links.jsonp # change me
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: hidden
          value: post
      - name: 'title'
        field:
          element: text
          label: 'Title'
      - name: 'categories'
        field:
          element: text
          label: 'Category'
          placeholder: Example
      - name: 'tags'
        field:
          element: text
          label: Tag(s)
          value: []
          placeholder: [tag1, tag2, tag3, ...]
